---
- hosts: all
  become: true
  gather_facts: true

  vars_files:
    - defaults/main.yml

  tasks:
  - name: Accept login with password from sshd
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication no$'
      line: 'PasswordAuthentication yes'
      state: present
    notify:
      - Restart sshd

  - name: Set timezone
    community.general.timezone:
      name: Europe/Moscow

  - name: set up forward packages across routers
    sysctl:
      name: net.ipv4.conf.all.forwarding
      value: '1'
      state: present
    when: "'routers' in group_names"

  - name: Asynchronous routing accept
    sysctl:
      name: net.ipv4.conf.all.rp_filter
      value: '0'
      state: present

  - name: add gpg frrouting.org
    apt_key:
      url: "https://deb.frrouting.org/frr/keys.asc"
      state: present

  - name: add frr repo
    apt_repository:
      repo: 'deb https://deb.frrouting.org/frr {{ ansible_distribution_release }} frr-stable'
      state: present

  - name: Install soft
    ansible.builtin.apt:
      name:
        - vim
        - tcpdump
        - traceroute
        - nmap
      state: present
      update-cache: true

  - name: install FRR packages
    apt:
      name: 
        - frr
        - frr-pythontools
      state: present
    notify:
      - Activate ospf frr
      - Restart frr

  - name: Config frr
    ansible.builtin.template:
      src: frr.conf.j2
      dest: /etc/frr/frr.conf
      owner: frr
      group: frr
      mode: 0640
    notify: Restart frr
    tags:
      - setup_ospf

  handlers:

  - name: Restart sshd
    ansible.builtin.service:
      name: sshd
      state: restarted

  - name: Activate ospf frr
    ansible.builtin.replace:
      path: /etc/frr/daemons
      regexp: '^ospfd=no$'
      replace: 'ospfd=yes'
    notify:
      - Restart frr

  - name: Restart frr
    ansible.builtin.service:
      name: frr
      state: restarted
      enabled: true









